### ISSUE TITLE
pip install doesn't work properly

### ISSUE THREAD

**Issue by skrzypek** [jp74/django-model-publisher#7]
```
jakubnowak@MBP-Jakub:website $ pip install django-model-publisher
Downloading/unpacking django-model-publisher
  Could not find any downloads that satisfy the requirement django-model-publisher
Cleaning up...
No distributions at all found for django-model-publisher
Storing debug log for failure in /var/folders/hl/gvnsh9c17rjc3tylvp079nq80000gn/T/tmpOnGDoU
```

```
/usr/local/bin/pip run on Mon Jan 12 19:13:35 2015
Downloading/unpacking django-model-publisher
  Getting page https://pypi.python.org/simple/django-model-publisher/
  URLs to search for versions for django-model-publisher:
  * https://pypi.python.org/simple/django-model-publisher/
  Analyzing links from page https://pypi.python.org/simple/django-model-publisher/
  Could not find any downloads that satisfy the requirement django-model-publisher
Cleaning up...
  Removing temporary dir /private/var/folders/hl/gvnsh9c17rjc3tylvp079nq80000gn/T/pip_build_jakubnowak...
No distributions at all found for django-model-publisher
Exception information:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for django-model-publisher
```

**Comment by bashu** [comment]
I think this one already fixed

**Comment by leesolway** [comment]
This has been fixed.. and we'll push a new version shortly.
